theme = "hugo-creative-portfolio-theme"
languageCode = "ja"
title = "Serendipity Phone"
baseurl = "https://shuzon.github.io/serendipity-phone"
canonifyurls = true
hasCJKLanguage = "true"

[params]
  style = "default"
  SubTitle = "Meet the best head phone"
  Author = "Shuzo Nakamura"
  Email = "d.namu.r21@gmail.com"
  copyright = "Copyright: © 2018- <br />Serendipity Phone in Tokyo, Japan"

  sidebarAbout = [
    "Let's Find The Best HeadPhone<br />in Your Life",
    "1. Choose head phone",
    "2. Just listen it!",
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "/headphone/"
  home = true

  [params.social]
  facebook      = "https://www.facebook.com/nakamura.syuzo"
  twitter       = "https://twitter.com/ShuzoN__"
  instagram     = "https://www.instagram.com/shuzon21/"
  github        = "https://github.com/shuzon"
